service: adv-intimacoes

frameworkVersion: "4"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  environment:
    GOOGLE_CREDENTIALS: ${env:GOOGLE_CREDENTIALS} 
    API_KEY:  ${env:API_KEY} 
    NODE_ENV: production
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
        - ssm:GetParameters
        - ssm:GetParameterHistory
      Resource: 
        - "arn:aws:ssm:${self:provider.region}:*:parameter/GOOGLE_CREDENTIALS"
        - "arn:aws:ssm:${self:provider.region}:*:parameter/API_KEY"

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node18'
    platform: 'node'
    concurrency: 10

package:
  patterns:
    - "!node_modules/.prisma/**"
    - "!node_modules/@prisma/**"
    - "!tests/**"
    - "!coverage/**"
    - "!.git/**"
    - "!README.md"

functions:
  processIntimacoes:
    handler: dist/index.handler
    timeout: 300 # 5 minutos
    events:
      - schedule:
          rate: rate(1 minute) # cron(*/10 9-11 ? * MON-FRI *) # Executa a cada 10 minutos das 9h às 12h em dias úteis
          enabled: true
          description: "Processa intimações a cada 10 minutos em dias úteis"
