service: supabase-sheets-sync

frameworkVersion: "4"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_REGION}
  environment:
    # SUPABASE_URL: ${env:SUPABASE_URL}
    # SUPABASE_KEY: ${env:SUPABASE_KEY}
    # DYNAMODB_TABLE: ${env:DYNAMODB_TABLE}
    # GOOGLE_CLIENT_EMAIL: ${env:GOOGLE_CLIENT_EMAIL}
    # GOOGLE_PRIVATE_KEY: ${env:GOOGLE_PRIVATE_KEY}
    # USERS_SHEETS_ID: ${env:USERS_SHEETS_ID}
    # PAYMENTS_SHEETS_ID: ${env:PAYMENTS_SHEETS_ID}
    # DEPENDENTS_SHEETS_ID: ${env:DEPENDENTS_SHEETS_ID}
    GOOGLE_CREDENTIALS: ${ssm:GOOGLE_CREDENTIALS, ssm:/GOOGLE_CREDENTIALS, null}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
        - ssm:GetParameters
        - ssm:GetParameterHistory
      Resource: "arn:aws:ssm:${self:provider.region}:*:parameter/GOOGLE_CREDENTIALS"

functions:
  sync:
    handler: search.main
    timeout: 30
    events:
      - schedule:
        cron: "0 11-21 ? * 2-6 *"

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ["aws-sdk"]
    target: "node18"
    platform: "node"
    concurrency: 10
