service: adv-intimacoes

frameworkVersion: "4"

plugins:
  - serverless-offline
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_REGION}
  environment:
    GOOGLE_CREDENTIALS: ${ssm:GOOGLE_CREDENTIALS}
    API_KEY: ${ssm:API_KEY}
    NODE_ENV: ${opt:stage, 'dev'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
        - ssm:GetParameters
        - ssm:GetParameterHistory
      Resource: 
        - "arn:aws:ssm:${self:provider.region}:*:parameter/GOOGLE_CREDENTIALS"
        - "arn:aws:ssm:${self:provider.region}:*:parameter/API_KEY"

functions:
  processIntimacoes:
    handler: dist/index.handler
    timeout: 300 # 5 minutos
    events:
      - schedule:
          rate: cron(0 11-16 ? * MON-FRI *) # Executa de hora em hora das 8h às 16h em dias úteis
          enabled: true
          description: "Processa intimações a cada hora em dias úteis"

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ["aws-sdk"]
    target: "node18"
    platform: "node"
    concurrency: 10

package:
  patterns:
    - "!node_modules/.prisma/**"
    - "!node_modules/@prisma/**"
    - "!tests/**"
    - "!coverage/**"
    - "!.git/**"
    - "!README.md"
