service: adv-intimacoes

frameworkVersion: "4"

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  profile: adv-intimacoes  # Força usar este perfil
  environment:
    GOOGLE_CREDENTIALS: ${env:GOOGLE_CREDENTIALS} 
    API_KEY:  ${env:API_KEY} 
    NODE_ENV: production
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
        - ssm:GetParameters
        - ssm:GetParameterHistory
      Resource: 
        - "arn:aws:ssm:${self:provider.region}:*:parameter/GOOGLE_CREDENTIALS"
        - "arn:aws:ssm:${self:provider.region}:*:parameter/API_KEY"

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node18'
    platform: 'node'
    mainFields: ['module', 'main']
    outdir: 'dist'

package:
  patterns:
    - "!node_modules/.prisma/**"
    - "!node_modules/@prisma/**"
    - "!tests/**"
    - "!coverage/**"
    - "!.git/**"
    - "!README.md"

functions:
  processIntimacoes:
    handler: src/index.handler
    timeout: 300 # 5 minutos
    events:
      - schedule:
          rate: cron(0 9-12 ? * MON-FRI *) # Executa às 9h, 10h, 11h e 12h em dias úteis
          enabled: true
          description: "Processa intimações a cada hora (9h, 10h, 11h, 12h) em dias úteis"
